services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181


  activemq:
    image: webcenter/activemq:latest
    ports:
    - "8161:8161"
    - "61616:61616"
    environment:
    - ACTIVEMQ_NAME=activemq
    - ACTIVEMQ_USERNAME=admin
    - ACTIVEMQ_PASSWORD=password

  db:
    image: ubuntu/mysql
    ports:
      - '30306:3306'
    expose:
      - '30306'
    environment:
      MYSQL_ROOT_PASSWORD: pass

